
import "./globals.css";
import { GeistSans } from 'geist/font/sans';


export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }) {
  return (
    <html lang="en"  className={`${GeistSans.variable} font-sans`} >
      <body >{children}</body>
    </html>
  );
}
